{
    'name' : 'Hospital',
    'version': '1.0',
    'depends' : ['base', 'hospital_staff'],
    'author': 'Jonah',
    'category': 'Hospital',
    'summary': 'Gestion des Hopitaux et des pharmacies',
    'description': "Gestion des Hopitaux et des pharmacies",
    'data': [
        'views/hospital_patient_views.xml',
        'views/hospital_disease_views.xml',
        'views/hospital_symptom_views.xml',
        'views/hospital_consultation_line_views.xml',
        'views/hospital_consultation_views.xml',
        'views/hospital_medicament_views.xml',
        'views/hospital_round_views.xml',
        'views/hospital_round_line_views.xml',
        'views/hospital_patient_views.xml',
        'views/hospital_patient_request_views.xml',
        'report/hospital_round_reports.xml',
        'report/hospital_round_report_templates.xml',
        'report/hospital_patient_record_reports.xml',
        'report/hospital_patient_record_templates.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}