from . import hospital_patient
from . import hospital_disease
from . import hospital_symptom
from . import hospital_symptom
from . import hospital_consultation_line
from . import hospital_consultation
from . import hospital_medicament
from . import hospital_round
from . import hospital_round_line
from . import hospital_patient_request